-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.126 Production Release
--  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
-- 
--  Generated by:   oh1015@EEWS104A-006
--  Generated date: Tue Mar 08 14:42:22 2016
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    mean_vga_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.mean_vga_mux_pkg.ALL;


ENTITY mean_vga_core IS
  PORT(
    clk : IN STD_LOGIC;
    en : IN STD_LOGIC;
    arst_n : IN STD_LOGIC;
    vin_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (749 DOWNTO 0);
    vout_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (149 DOWNTO 0)
  );
END mean_vga_core;

ARCHITECTURE v4 OF mean_vga_core IS
  -- Default Constants

BEGIN
  -- Default Constant Signal Assignments

  core : PROCESS
    -- Interconnect Declarations
    VARIABLE regs_regs_0_1_sva : STD_LOGIC_VECTOR (29 DOWNTO 0);
    VARIABLE regs_regs_0_1_lpi_2 : STD_LOGIC_VECTOR (29 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg1_lpi_2 : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg2_lpi_2 : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_1_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg3_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg5_lpi_2 : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg6_lpi_2 : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg4_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg7_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg9_lpi_2 : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg10_lpi_2 : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg8_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg11_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg13_lpi_2 : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg14_lpi_2 : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg12_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg15_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg17_lpi_2 : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg18_lpi_2 : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg16_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg19_lpi_2 : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE FRAME_p_1_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE regs_regs_0_1_lpi_3 : STD_LOGIC_VECTOR (29 DOWNTO 0);
    VARIABLE regs_operator_din_1_sva : STD_LOGIC_VECTOR (29 DOWNTO 0);
    VARIABLE regs_regs_0_1_lpi_3_dfm : STD_LOGIC_VECTOR (29 DOWNTO 0);
    VARIABLE FRAME_acc_6_psp_sva : STD_LOGIC_VECTOR (11 DOWNTO 0);
    VARIABLE acc_1_psp_sva : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE acc_imod_1_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE FRAME_acc_7_psp_sva : STD_LOGIC_VECTOR (11 DOWNTO 0);
    VARIABLE FRAME_or_psp_sva : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE FRAME_or_3_psp_sva : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE equal_tmp : STD_LOGIC;
    VARIABLE equal_tmp_1 : STD_LOGIC;
    VARIABLE equal_tmp_2 : STD_LOGIC;
    VARIABLE equal_tmp_3 : STD_LOGIC;
    VARIABLE io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm : STD_LOGIC_VECTOR (3 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm : STD_LOGIC_VECTOR (5 DOWNTO 0);
    VARIABLE io_read_vout_rsc_d_sdt_1_lpi_2_dfm : STD_LOGIC_VECTOR (9 DOWNTO 0);
    VARIABLE FRAME_p_1_sva_1 : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE SHIFT_acc_1_psp : STD_LOGIC_VECTOR (2 DOWNTO 0);
    VARIABLE slc_slc : STD_LOGIC_VECTOR (629 DOWNTO 0);
    VARIABLE FRAME_slc_itm : STD_LOGIC;
    VARIABLE FRAME_or_20_cse : STD_LOGIC;
    VARIABLE SHIFT_i_1_sva_2_sg1 : STD_LOGIC;
    VARIABLE SHIFT_i_1_sva_3 : STD_LOGIC_VECTOR (1 DOWNTO 0);

  BEGIN
    core_rlp : LOOP
      -- C-Step 0 of Loop 'core_rlp'
      regs_regs_0_1_sva := STD_LOGIC_VECTOR'("000000000000000000000000000000");
      main : LOOP
        -- C-Step 0 of Loop 'main'
        io_read_vout_rsc_d_sdt_sg19_lpi_2 := io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg16_lpi_2 := io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg18_lpi_2 := io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg17_lpi_2 := io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg15_lpi_2 := io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg12_lpi_2 := io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg14_lpi_2 := io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg13_lpi_2 := io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg11_lpi_2 := io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg8_lpi_2 := io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg10_lpi_2 := io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg9_lpi_2 := io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg7_lpi_2 := io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg4_lpi_2 := io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg6_lpi_2 := io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg5_lpi_2 := io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg3_lpi_2 := io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_1_lpi_2 := io_read_vout_rsc_d_sdt_1_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg2_lpi_2 := io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm;
        io_read_vout_rsc_d_sdt_sg1_lpi_2 := io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm;
        regs_regs_0_1_lpi_2 := regs_regs_0_1_sva;
        FRAME_p_1_sva := STD_LOGIC_VECTOR'("000");
        WAIT UNTIL (clk'EVENT AND ( clk = '1' ) AND ( ( en = '1' ) ) ) OR ( arst_n
            = '0' );
        EXIT core_rlp WHEN ( arst_n = '0' );
        -- C-Step 1 of Loop 'main'
        FRAME : LOOP
          -- C-Step 0 of Loop 'FRAME'
          regs_regs_0_1_lpi_3 := regs_regs_0_1_lpi_2;
          SHIFT_i_1_sva_3 := STD_LOGIC_VECTOR'("00");
          SHIFT_i_1_sva_2_sg1 := '1';
          WAIT UNTIL (clk'EVENT AND ( clk = '1' ) AND ( ( en = '1' ) ) ) OR ( arst_n
              = '0' );
          EXIT core_rlp WHEN ( arst_n = '0' );
          -- C-Step 1 of Loop 'FRAME'
          slc_slc := vin_rsc_mgc_in_wire_d(629 DOWNTO 0);
          regs_operator_din_1_sva := MUX_v_30_8_2((slc_slc(29 DOWNTO 0)) & (slc_slc(179
              DOWNTO 150)) & (slc_slc(329 DOWNTO 300)) & (slc_slc(479 DOWNTO 450))
              & (slc_slc(629 DOWNTO 600)) & STD_LOGIC_VECTOR'("000000000000000000000000000000")
              & STD_LOGIC_VECTOR'("000000000000000000000000000000") & STD_LOGIC_VECTOR'("000000000000000000000000000000"),
              FRAME_p_1_sva);
          SHIFT : LOOP
            -- C-Step 0 of Loop 'SHIFT'
            WAIT UNTIL (clk'EVENT AND ( clk = '1' ) AND ( ( en = '1' ) ) ) OR ( arst_n
                = '0' );
            EXIT core_rlp WHEN ( arst_n = '0' );
            -- C-Step 1 of Loop 'SHIFT'
            regs_regs_0_1_lpi_3_dfm := MUX_v_30_2_2(regs_operator_din_1_sva & regs_regs_0_1_lpi_3,
                SHIFT_i_1_sva_2_sg1 OR (SHIFT_i_1_sva_3(1)) OR (SHIFT_i_1_sva_3(0)));
            SHIFT_acc_1_psp := STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR(SHIFT_i_1_sva_2_sg1)
                & SHIFT_i_1_sva_3) + CONV_SIGNED(CONV_SIGNED('1', 1), 3), 3));
            EXIT SHIFT WHEN ( (SHIFT_acc_1_psp(2)) = '1' );
            SHIFT_i_1_sva_3 := SHIFT_acc_1_psp(1 DOWNTO 0);
            SHIFT_i_1_sva_2_sg1 := '0';
            regs_regs_0_1_lpi_3 := regs_regs_0_1_lpi_3_dfm;
          END LOOP SHIFT;

          equal_tmp := (FRAME_p_1_sva(0)) AND (NOT((FRAME_p_1_sva(2)) OR (FRAME_p_1_sva(1))));
          equal_tmp_1 := (FRAME_p_1_sva(1)) AND (NOT((FRAME_p_1_sva(2)) OR (FRAME_p_1_sva(0))));
          equal_tmp_2 := (FRAME_p_1_sva(1)) AND (FRAME_p_1_sva(0)) AND (NOT (FRAME_p_1_sva(2)));
          equal_tmp_3 := (FRAME_p_1_sva(2)) AND (NOT((FRAME_p_1_sva(1)) OR (FRAME_p_1_sva(0))));
          WAIT UNTIL (clk'EVENT AND ( clk = '1' ) AND ( ( en = '1' ) ) ) OR ( arst_n
              = '0' );
          EXIT core_rlp WHEN ( arst_n = '0' );
          -- C-Step 2 of Loop 'FRAME'
          FRAME_acc_6_psp_sva := STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(regs_regs_0_1_lpi_3_dfm(9
              DOWNTO 0)), 11) + CONV_UNSIGNED(UNSIGNED(regs_regs_0_1_lpi_3_dfm(19
              DOWNTO 10)), 11), 12) + CONV_UNSIGNED(UNSIGNED(regs_regs_0_1_lpi_3_dfm(29
              DOWNTO 20)), 12), 12));
          acc_1_psp_sva := STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED((readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED((readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED'((NOT
              (FRAME_acc_6_psp_sva(3))) & '1'), 3) + CONV_UNSIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(4))
              & (FRAME_acc_6_psp_sva(8))), 3), 3)), 1, 2)) & TO_STDLOGICVECTOR('1')),
              4) + CONV_UNSIGNED(UNSIGNED((readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED'((NOT
              (FRAME_acc_6_psp_sva(5))) & '1'), 3) + CONV_UNSIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(6))
              & (NOT (FRAME_acc_6_psp_sva(7)))), 3), 3)), 1, 2)) & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(10))),
              4), 4)), 1, 3)) & TO_STDLOGICVECTOR('1')), 5) + CONV_UNSIGNED(UNSIGNED((readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED'((NOT
              (FRAME_acc_6_psp_sva(1))) & '1'), 3) + CONV_UNSIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(2))
              & (NOT (FRAME_acc_6_psp_sva(9)))), 3), 3)), 1, 2)) & TO_STDLOGICVECTOR(NOT
              (FRAME_acc_6_psp_sva(11)))), 5), 5)), 1, 4)) + SIGNED(STD_LOGIC_VECTOR'("101")
              & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(0))), 4));
          acc_imod_1_sva := STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(acc_1_psp_sva(1),
              1), 2) + CONV_SIGNED(CONV_UNSIGNED(acc_1_psp_sva(0), 1), 2), 3) + CONV_SIGNED(SIGNED(acc_1_psp_sva(3
              DOWNTO 2)), 3), 3));
          FRAME_acc_7_psp_sva := STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(UNSIGNED(TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(11))
              & STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(11))
              & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(11))
              & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(11))
              & TO_STDLOGICVECTOR('0') & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(FRAME_acc_6_psp_sva(7),
              1),2))), 9) + CONV_UNSIGNED(UNSIGNED(readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(9))
              & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(9))
              & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(9))
              & TO_STDLOGICVECTOR('0') & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(FRAME_acc_6_psp_sva(5),
              1),2)) & TO_STDLOGICVECTOR('1')) + CONV_UNSIGNED(UNSIGNED((readslice(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(7))
              & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(5))
              & TO_STDLOGICVECTOR('0') & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(FRAME_acc_6_psp_sva(9),
              1),2)) & TO_STDLOGICVECTOR('1')), 8) + CONV_UNSIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(6))
              & '0' & (FRAME_acc_6_psp_sva(6)) & '0' & (FRAME_acc_6_psp_sva(6)) &
              (acc_imod_1_sva(1))), 8), 8)), 1, 7)) & TO_STDLOGICVECTOR(NOT (readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED'('1'
              & (acc_imod_1_sva(0)) & '1') + CONV_SIGNED(UNSIGNED'((NOT (acc_imod_1_sva(1)))
              & (NOT (acc_imod_1_sva(2)))), 3), 3)), 2)))), 9), 9)), 1, 8)), 9),
              9))), 12) + CONV_SIGNED(CONV_SIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(10))
              & '0' & (FRAME_acc_6_psp_sva(10)) & '0' & (FRAME_acc_6_psp_sva(10))
              & '0' & (FRAME_acc_6_psp_sva(10)) & '0' & (FRAME_acc_6_psp_sva(10))),
              10) + CONV_SIGNED(SIGNED(readslice(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(8))
              & '0' & (FRAME_acc_6_psp_sva(8)) & '0' & (FRAME_acc_6_psp_sva(8)) &
              '0' & (FRAME_acc_6_psp_sva(8)) & '1'), 9) + CONV_SIGNED(SIGNED((readslice(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(SIGNED((readslice(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(SIGNED((readslice(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(UNSIGNED'((FRAME_acc_6_psp_sva(3))
              & (FRAME_acc_6_psp_sva(1)) & '1'), 4) + CONV_SIGNED(SIGNED'('1' & (FRAME_acc_6_psp_sva(2))
              & (FRAME_acc_6_psp_sva(3))), 4), 4)), 1, 3)) & TO_STDLOGICVECTOR('1')),
              5) + CONV_SIGNED(SIGNED((acc_1_psp_sva(3 DOWNTO 2)) & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(4))),
              5), 5)), 1, 4)) & TO_STDLOGICVECTOR('1')), 7) + CONV_SIGNED(UNSIGNED(TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(7))
              & TO_STDLOGICVECTOR(FRAME_acc_6_psp_sva(4)) & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(FRAME_acc_6_psp_sva(11),
              1),2)) & TO_STDLOGICVECTOR(acc_1_psp_sva(1))), 7), 7)), 1, 6)) & TO_STDLOGICVECTOR(NOT
              (acc_imod_1_sva(2)))), 9), 9)), 1, 8)), 10), 12), 12));
          FRAME_or_psp_sva := (FRAME_acc_7_psp_sva(9 DOWNTO 0)) OR STD_LOGIC_VECTOR(UNSIGNED'("0000")
              & UNSIGNED(CONV_SIGNED(SIGNED(FRAME_acc_7_psp_sva(11 DOWNTO 10)),6)));
          FRAME_or_3_psp_sva := (FRAME_acc_7_psp_sva(5 DOWNTO 0)) OR STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(FRAME_acc_7_psp_sva(11
              DOWNTO 10)),6));
          io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg19_lpi_2
              & FRAME_or_psp_sva, equal_tmp_3);
          io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm := MUX_v_4_2_2(io_read_vout_rsc_d_sdt_sg18_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 6)), equal_tmp_3);
          io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm := MUX_v_6_2_2(io_read_vout_rsc_d_sdt_sg17_lpi_2
              & FRAME_or_3_psp_sva, equal_tmp_3);
          io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg16_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 0)), equal_tmp_3);
          io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg15_lpi_2
              & FRAME_or_psp_sva, equal_tmp_2);
          io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm := MUX_v_4_2_2(io_read_vout_rsc_d_sdt_sg14_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 6)), equal_tmp_2);
          io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm := MUX_v_6_2_2(io_read_vout_rsc_d_sdt_sg13_lpi_2
              & FRAME_or_3_psp_sva, equal_tmp_2);
          io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg12_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 0)), equal_tmp_2);
          io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg11_lpi_2
              & FRAME_or_psp_sva, equal_tmp_1);
          io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm := MUX_v_4_2_2(io_read_vout_rsc_d_sdt_sg10_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 6)), equal_tmp_1);
          io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm := MUX_v_6_2_2(io_read_vout_rsc_d_sdt_sg9_lpi_2
              & FRAME_or_3_psp_sva, equal_tmp_1);
          io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg8_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 0)), equal_tmp_1);
          io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg7_lpi_2
              & FRAME_or_psp_sva, equal_tmp);
          io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm := MUX_v_4_2_2(io_read_vout_rsc_d_sdt_sg6_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 6)), equal_tmp);
          io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm := MUX_v_6_2_2(io_read_vout_rsc_d_sdt_sg5_lpi_2
              & FRAME_or_3_psp_sva, equal_tmp);
          io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm := MUX_v_10_2_2(io_read_vout_rsc_d_sdt_sg4_lpi_2
              & (FRAME_acc_7_psp_sva(9 DOWNTO 0)), equal_tmp);
          FRAME_or_20_cse := equal_tmp OR equal_tmp_1 OR equal_tmp_2 OR equal_tmp_3;
          io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm := MUX_v_10_2_2(FRAME_or_psp_sva &
              io_read_vout_rsc_d_sdt_sg3_lpi_2, FRAME_or_20_cse);
          io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm := MUX_v_4_2_2((FRAME_acc_7_psp_sva(9
              DOWNTO 6)) & io_read_vout_rsc_d_sdt_sg2_lpi_2, FRAME_or_20_cse);
          io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm := MUX_v_6_2_2(FRAME_or_3_psp_sva
              & io_read_vout_rsc_d_sdt_sg1_lpi_2, FRAME_or_20_cse);
          io_read_vout_rsc_d_sdt_1_lpi_2_dfm := MUX_v_10_2_2((FRAME_acc_7_psp_sva(9
              DOWNTO 0)) & io_read_vout_rsc_d_sdt_1_lpi_2, FRAME_or_20_cse);
          vout_rsc_mgc_out_stdreg_d <= io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm & io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm
              & io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm & io_read_vout_rsc_d_sdt_1_lpi_2_dfm;
          FRAME_p_1_sva_1 := STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(FRAME_p_1_sva)
              + CONV_UNSIGNED(CONV_UNSIGNED('1', 1), 3), 3));
          FRAME_slc_itm := readindex(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(UNSIGNED(FRAME_p_1_sva_1),
              4) + SIGNED'("1011"), 4)), 3);
          WAIT UNTIL (clk'EVENT AND ( clk = '1' ) AND ( ( en = '1' ) ) ) OR ( arst_n
              = '0' );
          EXIT core_rlp WHEN ( arst_n = '0' );
          -- C-Step 3 of Loop 'FRAME'
          EXIT FRAME WHEN ( FRAME_slc_itm = '0' );
          FRAME_p_1_sva := FRAME_p_1_sva_1;
          io_read_vout_rsc_d_sdt_sg19_lpi_2 := io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg18_lpi_2 := io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg17_lpi_2 := io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg16_lpi_2 := io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg15_lpi_2 := io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg14_lpi_2 := io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg13_lpi_2 := io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg12_lpi_2 := io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg11_lpi_2 := io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg10_lpi_2 := io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg9_lpi_2 := io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg8_lpi_2 := io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg7_lpi_2 := io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg6_lpi_2 := io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg5_lpi_2 := io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg4_lpi_2 := io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg3_lpi_2 := io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg2_lpi_2 := io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_sg1_lpi_2 := io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm;
          io_read_vout_rsc_d_sdt_1_lpi_2 := io_read_vout_rsc_d_sdt_1_lpi_2_dfm;
          regs_regs_0_1_lpi_2 := regs_regs_0_1_lpi_3_dfm;
        END LOOP FRAME;

        regs_regs_0_1_sva := regs_regs_0_1_lpi_3_dfm;
      END LOOP main;

    END LOOP core_rlp;

    SHIFT_i_1_sva_3 := STD_LOGIC_VECTOR'("00");
    SHIFT_i_1_sva_2_sg1 := '0';
    FRAME_or_20_cse := '0';
    FRAME_slc_itm := '0';
    slc_slc := STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
    SHIFT_acc_1_psp := STD_LOGIC_VECTOR'("000");
    FRAME_p_1_sva_1 := STD_LOGIC_VECTOR'("000");
    io_read_vout_rsc_d_sdt_1_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg1_lpi_2_dfm := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg2_lpi_2_dfm := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg3_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg4_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg5_lpi_2_dfm := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg6_lpi_2_dfm := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg7_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg8_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg9_lpi_2_dfm := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg10_lpi_2_dfm := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg11_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg12_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg13_lpi_2_dfm := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg14_lpi_2_dfm := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg15_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg16_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg17_lpi_2_dfm := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg18_lpi_2_dfm := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg19_lpi_2_dfm := STD_LOGIC_VECTOR'("0000000000");
    equal_tmp_3 := '0';
    equal_tmp_2 := '0';
    equal_tmp_1 := '0';
    equal_tmp := '0';
    FRAME_or_3_psp_sva := STD_LOGIC_VECTOR'("000000");
    FRAME_or_psp_sva := STD_LOGIC_VECTOR'("0000000000");
    FRAME_acc_7_psp_sva := STD_LOGIC_VECTOR'("000000000000");
    acc_imod_1_sva := STD_LOGIC_VECTOR'("000");
    acc_1_psp_sva := STD_LOGIC_VECTOR'("0000");
    FRAME_acc_6_psp_sva := STD_LOGIC_VECTOR'("000000000000");
    regs_regs_0_1_lpi_3_dfm := STD_LOGIC_VECTOR'("000000000000000000000000000000");
    regs_operator_din_1_sva := STD_LOGIC_VECTOR'("000000000000000000000000000000");
    regs_regs_0_1_lpi_3 := STD_LOGIC_VECTOR'("000000000000000000000000000000");
    FRAME_p_1_sva := STD_LOGIC_VECTOR'("000");
    io_read_vout_rsc_d_sdt_sg19_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg16_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg18_lpi_2 := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg17_lpi_2 := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg15_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg12_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg14_lpi_2 := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg13_lpi_2 := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg11_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg8_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg10_lpi_2 := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg9_lpi_2 := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg7_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg4_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg6_lpi_2 := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg5_lpi_2 := STD_LOGIC_VECTOR'("000000");
    io_read_vout_rsc_d_sdt_sg3_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_1_lpi_2 := STD_LOGIC_VECTOR'("0000000000");
    io_read_vout_rsc_d_sdt_sg2_lpi_2 := STD_LOGIC_VECTOR'("0000");
    io_read_vout_rsc_d_sdt_sg1_lpi_2 := STD_LOGIC_VECTOR'("000000");
    regs_regs_0_1_lpi_2 := STD_LOGIC_VECTOR'("000000000000000000000000000000");
    regs_regs_0_1_sva := STD_LOGIC_VECTOR'("000000000000000000000000000000");
    vout_rsc_mgc_out_stdreg_d <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
  END PROCESS core;

END v4;

-- ------------------------------------------------------------------
--  Design Unit:    mean_vga
--  Generated from file(s):
--    7) $PROJECT_HOME/../provided_files/student_files_2015/prj2/catapult_proj/vga_blur/blur.c
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.mean_vga_mux_pkg.ALL;


ENTITY mean_vga IS
  PORT(
    vin_rsc_z : IN STD_LOGIC_VECTOR (749 DOWNTO 0);
    vout_rsc_z : OUT STD_LOGIC_VECTOR (149 DOWNTO 0);
    clk : IN STD_LOGIC;
    en : IN STD_LOGIC;
    arst_n : IN STD_LOGIC
  );
END mean_vga;

ARCHITECTURE v4 OF mean_vga IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL vin_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (749 DOWNTO 0);
  SIGNAL vout_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (149 DOWNTO 0);

  SIGNAL vin_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (749 DOWNTO 0);
  SIGNAL vin_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (749 DOWNTO 0);

  SIGNAL vout_rsc_mgc_out_stdreg_d_1 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL vout_rsc_mgc_out_stdreg_z : STD_LOGIC_VECTOR (149 DOWNTO 0);

  COMPONENT mean_vga_core
    PORT(
      clk : IN STD_LOGIC;
      en : IN STD_LOGIC;
      arst_n : IN STD_LOGIC;
      vin_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (749 DOWNTO 0);
      vout_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (149 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL mean_vga_core_inst_vin_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (749 DOWNTO
      0);
  SIGNAL mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (149 DOWNTO
      0);

BEGIN
  -- Default Constant Signal Assignments

  vin_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 1,
      width => 750
      )
    PORT MAP(
      d => vin_rsc_mgc_in_wire_d_1,
      z => vin_rsc_mgc_in_wire_z
    );
  vin_rsc_mgc_in_wire_d <= vin_rsc_mgc_in_wire_d_1;
  vin_rsc_mgc_in_wire_z <= vin_rsc_z;

  vout_rsc_mgc_out_stdreg : mgc_hls.mgc_ioport_comps.mgc_out_stdreg
    GENERIC MAP(
      rscid => 2,
      width => 150
      )
    PORT MAP(
      d => vout_rsc_mgc_out_stdreg_d_1,
      z => vout_rsc_mgc_out_stdreg_z
    );
  vout_rsc_mgc_out_stdreg_d_1 <= vout_rsc_mgc_out_stdreg_d;
  vout_rsc_z <= vout_rsc_mgc_out_stdreg_z;

  mean_vga_core_inst : mean_vga_core
    PORT MAP(
      clk => clk,
      en => en,
      arst_n => arst_n,
      vin_rsc_mgc_in_wire_d => mean_vga_core_inst_vin_rsc_mgc_in_wire_d,
      vout_rsc_mgc_out_stdreg_d => mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d
    );
  mean_vga_core_inst_vin_rsc_mgc_in_wire_d <= vin_rsc_mgc_in_wire_d;
  vout_rsc_mgc_out_stdreg_d <= mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d;

END v4;



