-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.126 Production Release
--  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
-- 
--  Generated by:   oh1015@EEWS104A-004
--  Generated date: Fri Mar 04 16:29:37 2016
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    mean_vga_core_fsm
--  FSM Module
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.mean_vga_mux_pkg.ALL;


ENTITY mean_vga_core_fsm IS
  PORT(
    clk : IN STD_LOGIC;
    en : IN STD_LOGIC;
    arst_n : IN STD_LOGIC;
    fsm_output : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
    st_SHIFT_tr0 : IN STD_LOGIC;
    st_ACC1_tr0 : IN STD_LOGIC;
    st_ACC2_tr0 : IN STD_LOGIC
  );
END mean_vga_core_fsm;

ARCHITECTURE v2 OF mean_vga_core_fsm IS
  -- Default Constants

  -- FSM State Type Declaration for mean_vga_core_fsm_1
  TYPE mean_vga_core_fsm_1_ST IS (st_main, st_SHIFT, st_ACC1, st_ACC2, st_main_1,
      st_main_2, st_main_3, st_main_4);

  SIGNAL state_var : mean_vga_core_fsm_1_ST;
  SIGNAL state_var_NS : mean_vga_core_fsm_1_ST;

BEGIN
  -- Default Constant Signal Assignments

  mean_vga_core_fsm_1 : PROCESS (st_SHIFT_tr0, st_ACC1_tr0, st_ACC2_tr0, state_var)
  BEGIN
    CASE state_var IS
      WHEN st_main =>
        fsm_output <= STD_LOGIC_VECTOR'("00000001");
        state_var_NS <= st_SHIFT;
      WHEN st_SHIFT =>
        fsm_output <= STD_LOGIC_VECTOR'("00000010");
        IF ( st_SHIFT_tr0 = '1' ) THEN
          state_var_NS <= st_ACC1;
        ELSE
          state_var_NS <= st_SHIFT;
        END IF;
      WHEN st_ACC1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00000100");
        IF ( st_ACC1_tr0 = '1' ) THEN
          state_var_NS <= st_ACC2;
        ELSE
          state_var_NS <= st_ACC1;
        END IF;
      WHEN st_ACC2 =>
        fsm_output <= STD_LOGIC_VECTOR'("00001000");
        IF ( st_ACC2_tr0 = '1' ) THEN
          state_var_NS <= st_main_1;
        ELSE
          state_var_NS <= st_ACC2;
        END IF;
      WHEN st_main_1 =>
        fsm_output <= STD_LOGIC_VECTOR'("00010000");
        state_var_NS <= st_main_2;
      WHEN st_main_2 =>
        fsm_output <= STD_LOGIC_VECTOR'("00100000");
        state_var_NS <= st_main_3;
      WHEN st_main_3 =>
        fsm_output <= STD_LOGIC_VECTOR'("01000000");
        state_var_NS <= st_main_4;
      WHEN st_main_4 =>
        fsm_output <= STD_LOGIC_VECTOR'("10000000");
        state_var_NS <= st_main;
      WHEN OTHERS =>
        fsm_output <= "00000000";
        state_var_NS <= st_main;
    END CASE;
  END PROCESS mean_vga_core_fsm_1;

  mean_vga_core_fsm_1_REG : PROCESS (clk, arst_n)
  BEGIN
    IF ( arst_n = '0' ) THEN
      state_var <= st_main;
    ELSIF clk'event AND ( clk = '1' ) THEN
      IF ( en = '1' ) THEN
        state_var <= state_var_NS;
      END IF;
    END IF;
  END PROCESS mean_vga_core_fsm_1_REG;

END v2;

-- ------------------------------------------------------------------
--  Design Unit:    mean_vga_core
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.mean_vga_mux_pkg.ALL;


ENTITY mean_vga_core IS
  PORT(
    clk : IN STD_LOGIC;
    en : IN STD_LOGIC;
    arst_n : IN STD_LOGIC;
    vin_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (149 DOWNTO 0);
    vout_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (29 DOWNTO 0)
  );
END mean_vga_core;

ARCHITECTURE v2 OF mean_vga_core IS
  -- Default Constants

  -- Output Reader Declarations
  SIGNAL vout_rsc_mgc_out_stdreg_d_drv : STD_LOGIC_VECTOR (29 DOWNTO 0);

  -- Interconnect Declarations
  SIGNAL fsm_output : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL and_dcpl : STD_LOGIC;
  SIGNAL or_dcpl_5 : STD_LOGIC;
  SIGNAL and_dcpl_4 : STD_LOGIC;
  SIGNAL and_dcpl_7 : STD_LOGIC;
  SIGNAL or_dcpl_9 : STD_LOGIC;
  SIGNAL regs_regs_2_sva : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_1_sva : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_3_sva : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_0_sva : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_0_lpi_2 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_2_lpi_2 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_1_lpi_2 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_3_lpi_2 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_4_lpi_2 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL red_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL green_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL blue_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_2_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_3_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_0_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_4_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_2_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_3_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_0_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_4_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_2_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_1_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_3_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_0_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_4_sva : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL regs_operator_din_sva : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_0_lpi_2_dfm : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_1_lpi_2_dfm : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_2_lpi_2_dfm : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_3_lpi_2_dfm : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL regs_regs_4_lpi_2_dfm : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL i_4_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL r_0_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_0_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_0_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_2_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_2_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_2_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_3_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_3_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_3_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_4_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_4_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_4_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL i_3_sva : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL red_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL green_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL blue_1_sva_1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL FRAME_acc_4_psp_sva : STD_LOGIC_VECTOR (11 DOWNTO 0);
  SIGNAL FRAME_acc_25_itm : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL FRAME_acc_42_itm : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL FRAME_acc_2_itm : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL FRAME_acc_59_psp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL FRAME_acc_57_psp : STD_LOGIC_VECTOR (5 DOWNTO 0);
  SIGNAL SHIFT_i_1_sva_2_sg1 : STD_LOGIC;
  SIGNAL SHIFT_i_1_sva_3 : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL z_out : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL z_out_1 : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL z_out_2 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL z_out_3 : STD_LOGIC_VECTOR (4 DOWNTO 0);
  SIGNAL z_out_4 : STD_LOGIC_VECTOR (10 DOWNTO 0);
  SIGNAL blue_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL green_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL red_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_4_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_4_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_4_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_3_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_3_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_3_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_2_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_2_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_2_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_1_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL b_0_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL g_0_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL r_0_sva_mx0w1 : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL regs_regs_4_lpi_3 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva : STD_LOGIC_VECTOR (149 DOWNTO
      0);
  SIGNAL acc_imod_sva : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL FRAME_acc_55_sdt : STD_LOGIC_VECTOR (3 DOWNTO 0);
  SIGNAL acc_imod_4_sva : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL FRAME_acc_45_sdt : STD_LOGIC_VECTOR (3 DOWNTO 0);
  SIGNAL acc_imod_2_sva : STD_LOGIC_VECTOR (6 DOWNTO 0);
  SIGNAL FRAME_acc_28_sdt : STD_LOGIC_VECTOR (3 DOWNTO 0);
  SIGNAL FRAME_acc_3_psp_sva : STD_LOGIC_VECTOR (11 DOWNTO 0);
  SIGNAL nand_1_tmp : STD_LOGIC;
  SIGNAL or_17_tmp : STD_LOGIC;
  SIGNAL or_18_tmp : STD_LOGIC;
  SIGNAL or_19_tmp : STD_LOGIC;

  SIGNAL ACC2_mux_2_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL ACC2_mux_1_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL ACC2_mux_nl : STD_LOGIC_VECTOR (15 DOWNTO 0);
  SIGNAL regs_operator_14_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_13_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_12_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_11_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_10_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_9_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_8_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_7_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_6_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_5_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_4_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_3_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_2_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_1_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL regs_operator_mux_nl : STD_LOGIC_VECTOR (9 DOWNTO 0);
  SIGNAL mux1h_74_nl : STD_LOGIC_VECTOR (3 DOWNTO 0);
  SIGNAL mux_nl : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL mux_62_nl : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL mux_58_nl : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL mux1h_73_nl : STD_LOGIC_VECTOR (2 DOWNTO 0);
  SIGNAL mux_59_nl : STD_LOGIC_VECTOR (1 DOWNTO 0);
  SIGNAL mux_61_nl : STD_LOGIC_VECTOR (6 DOWNTO 0);
  COMPONENT mean_vga_core_fsm
    PORT(
      clk : IN STD_LOGIC;
      en : IN STD_LOGIC;
      arst_n : IN STD_LOGIC;
      fsm_output : OUT STD_LOGIC_VECTOR (7 DOWNTO 0);
      st_SHIFT_tr0 : IN STD_LOGIC;
      st_ACC1_tr0 : IN STD_LOGIC;
      st_ACC2_tr0 : IN STD_LOGIC
    );
  END COMPONENT;
  SIGNAL mean_vga_core_fsm_inst_fsm_output : STD_LOGIC_VECTOR (7 DOWNTO 0);
  SIGNAL mean_vga_core_fsm_inst_st_SHIFT_tr0 : STD_LOGIC;
  SIGNAL mean_vga_core_fsm_inst_st_ACC1_tr0 : STD_LOGIC;
  SIGNAL mean_vga_core_fsm_inst_st_ACC2_tr0 : STD_LOGIC;

BEGIN
  -- Default Constant Signal Assignments

  -- Output Reader Assignments
  vout_rsc_mgc_out_stdreg_d <= vout_rsc_mgc_out_stdreg_d_drv;

  mean_vga_core_fsm_inst : mean_vga_core_fsm
    PORT MAP(
      clk => clk,
      en => en,
      arst_n => arst_n,
      fsm_output => mean_vga_core_fsm_inst_fsm_output,
      st_SHIFT_tr0 => mean_vga_core_fsm_inst_st_SHIFT_tr0,
      st_ACC1_tr0 => mean_vga_core_fsm_inst_st_ACC1_tr0,
      st_ACC2_tr0 => mean_vga_core_fsm_inst_st_ACC2_tr0
    );
  fsm_output <= mean_vga_core_fsm_inst_fsm_output;
  mean_vga_core_fsm_inst_st_SHIFT_tr0 <= z_out_3(2);
  mean_vga_core_fsm_inst_st_ACC1_tr0 <= NOT (z_out_1(2));
  mean_vga_core_fsm_inst_st_ACC2_tr0 <= NOT (z_out_1(2));

  nand_1_tmp <= NOT((SHIFT_i_1_sva_3(1)) AND (SHIFT_i_1_sva_3(0)));
  or_17_tmp <= (NOT (SHIFT_i_1_sva_3(1))) OR (SHIFT_i_1_sva_3(0));
  or_18_tmp <= (SHIFT_i_1_sva_3(1)) OR (NOT (SHIFT_i_1_sva_3(0)));
  or_19_tmp <= or_dcpl_5 OR SHIFT_i_1_sva_2_sg1;
  ACC2_mux_2_nl <= MUX_v_16_8_2(b_0_sva_1 & b_1_sva_1 & b_2_sva_1 & b_3_sva_1 & b_4_sva_1
      & STD_LOGIC_VECTOR'("0000000000000000") & STD_LOGIC_VECTOR'("0000000000000000")
      & STD_LOGIC_VECTOR'("0000000000000000"), i_3_sva);
  blue_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(blue_1_sva) + UNSIGNED(ACC2_mux_2_nl),
      16));
  ACC2_mux_1_nl <= MUX_v_16_8_2(g_0_sva_1 & g_1_sva_1 & g_2_sva_1 & g_3_sva_1 & g_4_sva_1
      & STD_LOGIC_VECTOR'("0000000000000000") & STD_LOGIC_VECTOR'("0000000000000000")
      & STD_LOGIC_VECTOR'("0000000000000000"), i_3_sva);
  green_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(green_1_sva) + UNSIGNED(ACC2_mux_1_nl),
      16));
  ACC2_mux_nl <= MUX_v_16_8_2(r_0_sva_1 & r_1_sva_1 & r_2_sva_1 & r_3_sva_1 & r_4_sva_1
      & STD_LOGIC_VECTOR'("0000000000000000") & STD_LOGIC_VECTOR'("0000000000000000")
      & STD_LOGIC_VECTOR'("0000000000000000"), i_3_sva);
  red_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(red_1_sva) + UNSIGNED(ACC2_mux_nl),
      16));
  regs_operator_14_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(129 DOWNTO 120))
      & (regs_regs_1_lpi_2_dfm(129 DOWNTO 120)) & (regs_regs_2_lpi_2_dfm(129 DOWNTO
      120)) & (regs_regs_3_lpi_2_dfm(129 DOWNTO 120)) & (regs_regs_4_lpi_2_dfm(129
      DOWNTO 120)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  b_4_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(b_4_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_14_mux_nl),
      16), 16));
  regs_operator_13_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(139 DOWNTO 130))
      & (regs_regs_1_lpi_2_dfm(139 DOWNTO 130)) & (regs_regs_2_lpi_2_dfm(139 DOWNTO
      130)) & (regs_regs_3_lpi_2_dfm(139 DOWNTO 130)) & (regs_regs_4_lpi_2_dfm(139
      DOWNTO 130)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  g_4_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(g_4_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_13_mux_nl),
      16), 16));
  regs_operator_12_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(149 DOWNTO 140))
      & (regs_regs_1_lpi_2_dfm(149 DOWNTO 140)) & (regs_regs_2_lpi_2_dfm(149 DOWNTO
      140)) & (regs_regs_3_lpi_2_dfm(149 DOWNTO 140)) & (regs_regs_4_lpi_2_dfm(149
      DOWNTO 140)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  r_4_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(r_4_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_12_mux_nl),
      16), 16));
  regs_operator_11_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(99 DOWNTO 90)) &
      (regs_regs_1_lpi_2_dfm(99 DOWNTO 90)) & (regs_regs_2_lpi_2_dfm(99 DOWNTO 90))
      & (regs_regs_3_lpi_2_dfm(99 DOWNTO 90)) & (regs_regs_4_lpi_2_dfm(99 DOWNTO
      90)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  b_3_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(b_3_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_11_mux_nl),
      16), 16));
  regs_operator_10_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(109 DOWNTO 100))
      & (regs_regs_1_lpi_2_dfm(109 DOWNTO 100)) & (regs_regs_2_lpi_2_dfm(109 DOWNTO
      100)) & (regs_regs_3_lpi_2_dfm(109 DOWNTO 100)) & (regs_regs_4_lpi_2_dfm(109
      DOWNTO 100)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  g_3_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(g_3_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_10_mux_nl),
      16), 16));
  regs_operator_9_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(119 DOWNTO 110))
      & (regs_regs_1_lpi_2_dfm(119 DOWNTO 110)) & (regs_regs_2_lpi_2_dfm(119 DOWNTO
      110)) & (regs_regs_3_lpi_2_dfm(119 DOWNTO 110)) & (regs_regs_4_lpi_2_dfm(119
      DOWNTO 110)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  r_3_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(r_3_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_9_mux_nl),
      16), 16));
  regs_operator_8_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(69 DOWNTO 60)) &
      (regs_regs_1_lpi_2_dfm(69 DOWNTO 60)) & (regs_regs_2_lpi_2_dfm(69 DOWNTO 60))
      & (regs_regs_3_lpi_2_dfm(69 DOWNTO 60)) & (regs_regs_4_lpi_2_dfm(69 DOWNTO
      60)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  b_2_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(b_2_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_8_mux_nl),
      16), 16));
  regs_operator_7_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(79 DOWNTO 70)) &
      (regs_regs_1_lpi_2_dfm(79 DOWNTO 70)) & (regs_regs_2_lpi_2_dfm(79 DOWNTO 70))
      & (regs_regs_3_lpi_2_dfm(79 DOWNTO 70)) & (regs_regs_4_lpi_2_dfm(79 DOWNTO
      70)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  g_2_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(g_2_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_7_mux_nl),
      16), 16));
  regs_operator_6_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(89 DOWNTO 80)) &
      (regs_regs_1_lpi_2_dfm(89 DOWNTO 80)) & (regs_regs_2_lpi_2_dfm(89 DOWNTO 80))
      & (regs_regs_3_lpi_2_dfm(89 DOWNTO 80)) & (regs_regs_4_lpi_2_dfm(89 DOWNTO
      80)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  r_2_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(r_2_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_6_mux_nl),
      16), 16));
  regs_operator_5_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(39 DOWNTO 30)) &
      (regs_regs_1_lpi_2_dfm(39 DOWNTO 30)) & (regs_regs_2_lpi_2_dfm(39 DOWNTO 30))
      & (regs_regs_3_lpi_2_dfm(39 DOWNTO 30)) & (regs_regs_4_lpi_2_dfm(39 DOWNTO
      30)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  b_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(b_1_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_5_mux_nl),
      16), 16));
  regs_operator_4_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(49 DOWNTO 40)) &
      (regs_regs_1_lpi_2_dfm(49 DOWNTO 40)) & (regs_regs_2_lpi_2_dfm(49 DOWNTO 40))
      & (regs_regs_3_lpi_2_dfm(49 DOWNTO 40)) & (regs_regs_4_lpi_2_dfm(49 DOWNTO
      40)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  g_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(g_1_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_4_mux_nl),
      16), 16));
  regs_operator_3_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(59 DOWNTO 50)) &
      (regs_regs_1_lpi_2_dfm(59 DOWNTO 50)) & (regs_regs_2_lpi_2_dfm(59 DOWNTO 50))
      & (regs_regs_3_lpi_2_dfm(59 DOWNTO 50)) & (regs_regs_4_lpi_2_dfm(59 DOWNTO
      50)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  r_1_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(r_1_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_3_mux_nl),
      16), 16));
  regs_operator_2_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(9 DOWNTO 0)) & (regs_regs_1_lpi_2_dfm(9
      DOWNTO 0)) & (regs_regs_2_lpi_2_dfm(9 DOWNTO 0)) & (regs_regs_3_lpi_2_dfm(9
      DOWNTO 0)) & (regs_regs_4_lpi_2_dfm(9 DOWNTO 0)) & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  b_0_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(b_0_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_2_mux_nl),
      16), 16));
  regs_operator_1_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(19 DOWNTO 10)) &
      (regs_regs_1_lpi_2_dfm(19 DOWNTO 10)) & (regs_regs_2_lpi_2_dfm(19 DOWNTO 10))
      & (regs_regs_3_lpi_2_dfm(19 DOWNTO 10)) & (regs_regs_4_lpi_2_dfm(19 DOWNTO
      10)) & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000") &
      STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  g_0_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(g_0_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_1_mux_nl),
      16), 16));
  regs_operator_mux_nl <= MUX_v_10_8_2((regs_regs_0_lpi_2_dfm(29 DOWNTO 20)) & (regs_regs_1_lpi_2_dfm(29
      DOWNTO 20)) & (regs_regs_2_lpi_2_dfm(29 DOWNTO 20)) & (regs_regs_3_lpi_2_dfm(29
      DOWNTO 20)) & (regs_regs_4_lpi_2_dfm(29 DOWNTO 20)) & STD_LOGIC_VECTOR'("0000000000")
      & STD_LOGIC_VECTOR'("0000000000") & STD_LOGIC_VECTOR'("0000000000"), i_4_sva);
  r_0_sva_mx0w1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(r_0_sva) + CONV_UNSIGNED(UNSIGNED(regs_operator_mux_nl),
      16), 16));
  regs_regs_4_lpi_3 <= MUX_v_150_2_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
      & regs_regs_4_lpi_2, or_dcpl_5 OR (NOT SHIFT_i_1_sva_2_sg1));
  SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva <= MUX_v_150_4_2(regs_regs_0_lpi_2
      & regs_regs_1_lpi_2 & regs_regs_2_lpi_2 & regs_regs_3_lpi_2, z_out_2(1 DOWNTO
      0));
  acc_imod_sva <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(UNSIGNED'("10011"),
      6) + CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (red_1_sva_1(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (red_1_sva_1(4)))),
      5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(red_1_sva_1(5)) & (red_1_sva_1(9
      DOWNTO 7))), 5), 6) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(red_1_sva_1(14))
      & STD_LOGIC_VECTOR'("00") & TO_STDLOGICVECTOR(red_1_sva_1(14))), 5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (red_1_sva_1(15))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (red_1_sva_1(5)))),
      5), 6), 6), 7) + CONV_SIGNED(CONV_SIGNED(SIGNED'((red_1_sva_1(6)) & '0' & (red_1_sva_1(6))
      & '0' & (red_1_sva_1(6))) + CONV_SIGNED(UNSIGNED(red_1_sva_1(3 DOWNTO 0)),
      5), 7) + CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(NOT (red_1_sva_1(13 DOWNTO 10))),
      5) + CONV_UNSIGNED(UNSIGNED((red_1_sva_1(9 DOWNTO 7)) & TO_STDLOGICVECTOR(red_1_sva_1(15))),
      5), 7), 7), 7));
  FRAME_acc_55_sdt <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (acc_imod_sva(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (acc_imod_sva(4))))
      + CONV_UNSIGNED(SIGNED(NOT (acc_imod_sva(6 DOWNTO 5))), 4), 4));
  acc_imod_4_sva <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(UNSIGNED'("10011"),
      6) + CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (blue_1_sva_1(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (blue_1_sva_1(4)))),
      5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(blue_1_sva_1(5)) & (blue_1_sva_1(9
      DOWNTO 7))), 5), 6) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(blue_1_sva_1(14))
      & STD_LOGIC_VECTOR'("00") & TO_STDLOGICVECTOR(blue_1_sva_1(14))), 5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (blue_1_sva_1(15))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (blue_1_sva_1(5)))),
      5), 6), 6), 7) + CONV_SIGNED(CONV_SIGNED(SIGNED'((blue_1_sva_1(6)) & '0' &
      (blue_1_sva_1(6)) & '0' & (blue_1_sva_1(6))) + CONV_SIGNED(UNSIGNED(blue_1_sva_1(3
      DOWNTO 0)), 5), 7) + CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(NOT (blue_1_sva_1(13
      DOWNTO 10))), 5) + CONV_UNSIGNED(UNSIGNED((blue_1_sva_1(9 DOWNTO 7)) & TO_STDLOGICVECTOR(blue_1_sva_1(15))),
      5), 7), 7), 7));
  FRAME_acc_45_sdt <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (acc_imod_4_sva(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (acc_imod_4_sva(4))))
      + CONV_UNSIGNED(SIGNED(NOT (acc_imod_4_sva(6 DOWNTO 5))), 4), 4));
  acc_imod_2_sva <= STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(UNSIGNED'("10011"),
      6) + CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (green_1_sva_1(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (green_1_sva_1(4)))),
      5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(green_1_sva_1(5)) & (green_1_sva_1(9
      DOWNTO 7))), 5), 6) + CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(green_1_sva_1(14))
      & STD_LOGIC_VECTOR'("00") & TO_STDLOGICVECTOR(green_1_sva_1(14))), 5) + CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (green_1_sva_1(15))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (green_1_sva_1(5)))),
      5), 6), 6), 7) + CONV_SIGNED(CONV_SIGNED(SIGNED'((green_1_sva_1(6)) & '0' &
      (green_1_sva_1(6)) & '0' & (green_1_sva_1(6))) + CONV_SIGNED(UNSIGNED(green_1_sva_1(3
      DOWNTO 0)), 5), 7) + CONV_SIGNED(CONV_UNSIGNED(UNSIGNED(NOT (green_1_sva_1(13
      DOWNTO 10))), 5) + CONV_UNSIGNED(UNSIGNED((green_1_sva_1(9 DOWNTO 7)) & TO_STDLOGICVECTOR(green_1_sva_1(15))),
      5), 7), 7), 7));
  FRAME_acc_28_sdt <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(NOT
      (acc_imod_2_sva(4))) & STD_LOGIC_VECTOR'("11") & TO_STDLOGICVECTOR(NOT (acc_imod_2_sva(4))))
      + CONV_UNSIGNED(SIGNED(NOT (acc_imod_2_sva(6 DOWNTO 5))), 4), 4));
  FRAME_acc_3_psp_sva <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED((green_1_sva_1(15
      DOWNTO 14)) & (green_1_sva_1(15 DOWNTO 14)) & TO_STDLOGICVECTOR('0') & FRAME_acc_57_psp),
      12) + CONV_UNSIGNED(SIGNED(z_out_4), 12), 12));
  and_dcpl <= NOT((fsm_output(7)) OR (fsm_output(1)));
  or_dcpl_5 <= (SHIFT_i_1_sva_3(1)) OR (SHIFT_i_1_sva_3(0));
  and_dcpl_4 <= NOT((fsm_output(3)) OR (fsm_output(0)));
  and_dcpl_7 <= NOT((fsm_output(2)) OR (fsm_output(0)));
  or_dcpl_9 <= (fsm_output(3)) OR (fsm_output(2));
  PROCESS (clk, arst_n)
  BEGIN
    IF ( arst_n = '0' ) THEN
      regs_regs_3_lpi_2 <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_2_lpi_2 <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_1_lpi_2 <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_0_lpi_2 <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      SHIFT_i_1_sva_3 <= STD_LOGIC_VECTOR'("00");
      vout_rsc_mgc_out_stdreg_d_drv <= STD_LOGIC_VECTOR'("000000000000000000000000000000");
      blue_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      green_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      red_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      b_4_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      g_4_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      r_4_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      b_3_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      g_3_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      r_3_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      b_2_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      g_2_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      r_2_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      b_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      g_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      r_1_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      b_0_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      g_0_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      r_0_sva <= STD_LOGIC_VECTOR'("0000000000000000");
      SHIFT_i_1_sva_2_sg1 <= '0';
      regs_regs_4_lpi_2 <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_operator_din_sva <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      i_4_sva <= STD_LOGIC_VECTOR'("000");
      regs_regs_4_lpi_2_dfm <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_3_lpi_2_dfm <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_2_lpi_2_dfm <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_1_lpi_2_dfm <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_0_lpi_2_dfm <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      i_3_sva <= STD_LOGIC_VECTOR'("000");
      b_4_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      b_3_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      b_2_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      b_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      b_0_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      g_4_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      g_3_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      g_2_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      g_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      g_0_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      r_4_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      r_3_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      r_2_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      r_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      r_0_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      green_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      blue_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      red_1_sva_1 <= STD_LOGIC_VECTOR'("0000000000000000");
      regs_regs_0_sva <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_2_sva <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_1_sva <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      regs_regs_3_sva <= STD_LOGIC_VECTOR'("000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000");
      FRAME_acc_2_itm <= STD_LOGIC_VECTOR'("0000000000");
      FRAME_acc_57_psp <= STD_LOGIC_VECTOR'("000000");
      FRAME_acc_25_itm <= STD_LOGIC_VECTOR'("0000000");
      FRAME_acc_59_psp <= STD_LOGIC_VECTOR'("000000");
      FRAME_acc_42_itm <= STD_LOGIC_VECTOR'("0000000");
      FRAME_acc_4_psp_sva <= STD_LOGIC_VECTOR'("000000000000");
    ELSIF clk'EVENT AND ( clk = '1' ) THEN
      IF ( en = '1' ) THEN
        regs_regs_3_lpi_2 <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_3_lpi_2 & regs_regs_3_sva, STD_LOGIC_VECTOR'(((NOT nand_1_tmp)
            AND (fsm_output(1))) & ((nand_1_tmp AND (fsm_output(1))) OR and_dcpl)
            & (fsm_output(7))));
        regs_regs_2_lpi_2 <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_2_lpi_2 & regs_regs_2_sva, STD_LOGIC_VECTOR'(((NOT or_17_tmp)
            AND (fsm_output(1))) & ((or_17_tmp AND (fsm_output(1))) OR and_dcpl)
            & (fsm_output(7))));
        regs_regs_1_lpi_2 <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_1_lpi_2 & regs_regs_1_sva, STD_LOGIC_VECTOR'(((NOT or_18_tmp)
            AND (fsm_output(1))) & ((or_18_tmp AND (fsm_output(1))) OR and_dcpl)
            & (fsm_output(7))));
        regs_regs_0_lpi_2 <= MUX1HOT_v_150_3_2(regs_operator_din_sva & regs_regs_0_lpi_2
            & regs_regs_0_sva, STD_LOGIC_VECTOR'(((NOT or_19_tmp) AND (fsm_output(1)))
            & ((or_19_tmp AND (fsm_output(1))) OR and_dcpl) & (fsm_output(7))));
        SHIFT_i_1_sva_3 <= (z_out_3(1 DOWNTO 0)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(fsm_output(1),
            1),2));
        vout_rsc_mgc_out_stdreg_d_drv <= MUX_v_30_2_2(vout_rsc_mgc_out_stdreg_d_drv
            & ((FRAME_acc_2_itm OR (STD_LOGIC_VECTOR'("00000000") & (FRAME_acc_3_psp_sva(11
            DOWNTO 10)))) & (FRAME_acc_3_psp_sva(9 DOWNTO 6)) & ((FRAME_acc_3_psp_sva(5
            DOWNTO 0)) OR (STD_LOGIC_VECTOR'("0000") & (FRAME_acc_4_psp_sva(11 DOWNTO
            10)))) & (FRAME_acc_4_psp_sva(9 DOWNTO 0))), fsm_output(6));
        blue_1_sva <= (MUX_v_16_2_2(blue_1_sva_mx0w1 & blue_1_sva, and_dcpl_4)) AND
            STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT (fsm_output(0)), 1),16));
        green_1_sva <= (MUX_v_16_2_2(green_1_sva_mx0w1 & green_1_sva, and_dcpl_4))
            AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT (fsm_output(0)), 1),16));
        red_1_sva <= (MUX_v_16_2_2(red_1_sva_mx0w1 & red_1_sva, and_dcpl_4)) AND
            STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT (fsm_output(0)), 1),16));
        b_4_sva <= (MUX_v_16_2_2(b_4_sva_mx0w1 & b_4_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        g_4_sva <= (MUX_v_16_2_2(g_4_sva_mx0w1 & g_4_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        r_4_sva <= (MUX_v_16_2_2(r_4_sva_mx0w1 & r_4_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        b_3_sva <= (MUX_v_16_2_2(b_3_sva_mx0w1 & b_3_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        g_3_sva <= (MUX_v_16_2_2(g_3_sva_mx0w1 & g_3_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        r_3_sva <= (MUX_v_16_2_2(r_3_sva_mx0w1 & r_3_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        b_2_sva <= (MUX_v_16_2_2(b_2_sva_mx0w1 & b_2_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        g_2_sva <= (MUX_v_16_2_2(g_2_sva_mx0w1 & g_2_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        r_2_sva <= (MUX_v_16_2_2(r_2_sva_mx0w1 & r_2_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        b_1_sva <= (MUX_v_16_2_2(b_1_sva_mx0w1 & b_1_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        g_1_sva <= (MUX_v_16_2_2(g_1_sva_mx0w1 & g_1_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        r_1_sva <= (MUX_v_16_2_2(r_1_sva_mx0w1 & r_1_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        b_0_sva <= (MUX_v_16_2_2(b_0_sva_mx0w1 & b_0_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        g_0_sva <= (MUX_v_16_2_2(g_0_sva_mx0w1 & g_0_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        r_0_sva <= (MUX_v_16_2_2(r_0_sva_mx0w1 & r_0_sva, and_dcpl_7)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT
            (fsm_output(0)), 1),16));
        SHIFT_i_1_sva_2_sg1 <= NOT (fsm_output(1));
        regs_regs_4_lpi_2 <= regs_regs_4_lpi_3;
        regs_operator_din_sva <= MUX_v_150_2_2(vin_rsc_mgc_in_wire_d & regs_operator_din_sva,
            fsm_output(1));
        i_4_sva <= (z_out_3(2 DOWNTO 0)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(fsm_output(2),
            1),3));
        regs_regs_4_lpi_2_dfm <= MUX_v_150_2_2(regs_regs_4_lpi_3 & regs_regs_4_lpi_2_dfm,
            fsm_output(2));
        regs_regs_3_lpi_2_dfm <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_3_lpi_2 & regs_regs_3_lpi_2_dfm, STD_LOGIC_VECTOR'((NOT(nand_1_tmp
            OR or_dcpl_9)) & (nand_1_tmp AND (NOT or_dcpl_9)) & or_dcpl_9));
        regs_regs_2_lpi_2_dfm <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_2_lpi_2 & regs_regs_2_lpi_2_dfm, STD_LOGIC_VECTOR'((NOT(or_17_tmp
            OR or_dcpl_9)) & (or_17_tmp AND (NOT or_dcpl_9)) & or_dcpl_9));
        regs_regs_1_lpi_2_dfm <= MUX1HOT_v_150_3_2(SHIFT_if_else_else_else_slc_regs_regs_ctmp_sva
            & regs_regs_1_lpi_2 & regs_regs_1_lpi_2_dfm, STD_LOGIC_VECTOR'((NOT(or_18_tmp
            OR or_dcpl_9)) & (or_18_tmp AND (NOT or_dcpl_9)) & or_dcpl_9));
        regs_regs_0_lpi_2_dfm <= MUX1HOT_v_150_3_2(regs_operator_din_sva & regs_regs_0_lpi_2
            & regs_regs_0_lpi_2_dfm, STD_LOGIC_VECTOR'((NOT(or_19_tmp OR or_dcpl_9))
            & (or_19_tmp AND (NOT or_dcpl_9)) & or_dcpl_9));
        i_3_sva <= (z_out_3(2 DOWNTO 0)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(fsm_output(3),
            1),3));
        b_4_sva_1 <= MUX_v_16_2_2(b_4_sva_mx0w1 & b_4_sva_1, fsm_output(3));
        b_3_sva_1 <= MUX_v_16_2_2(b_3_sva_mx0w1 & b_3_sva_1, fsm_output(3));
        b_2_sva_1 <= MUX_v_16_2_2(b_2_sva_mx0w1 & b_2_sva_1, fsm_output(3));
        b_1_sva_1 <= MUX_v_16_2_2(b_1_sva_mx0w1 & b_1_sva_1, fsm_output(3));
        b_0_sva_1 <= MUX_v_16_2_2(b_0_sva_mx0w1 & b_0_sva_1, fsm_output(3));
        g_4_sva_1 <= MUX_v_16_2_2(g_4_sva_mx0w1 & g_4_sva_1, fsm_output(3));
        g_3_sva_1 <= MUX_v_16_2_2(g_3_sva_mx0w1 & g_3_sva_1, fsm_output(3));
        g_2_sva_1 <= MUX_v_16_2_2(g_2_sva_mx0w1 & g_2_sva_1, fsm_output(3));
        g_1_sva_1 <= MUX_v_16_2_2(g_1_sva_mx0w1 & g_1_sva_1, fsm_output(3));
        g_0_sva_1 <= MUX_v_16_2_2(g_0_sva_mx0w1 & g_0_sva_1, fsm_output(3));
        r_4_sva_1 <= MUX_v_16_2_2(r_4_sva_mx0w1 & r_4_sva_1, fsm_output(3));
        r_3_sva_1 <= MUX_v_16_2_2(r_3_sva_mx0w1 & r_3_sva_1, fsm_output(3));
        r_2_sva_1 <= MUX_v_16_2_2(r_2_sva_mx0w1 & r_2_sva_1, fsm_output(3));
        r_1_sva_1 <= MUX_v_16_2_2(r_1_sva_mx0w1 & r_1_sva_1, fsm_output(3));
        r_0_sva_1 <= MUX_v_16_2_2(r_0_sva_mx0w1 & r_0_sva_1, fsm_output(3));
        green_1_sva_1 <= MUX_v_16_2_2(green_1_sva_1 & green_1_sva_mx0w1, fsm_output(3));
        blue_1_sva_1 <= MUX_v_16_2_2(blue_1_sva_1 & blue_1_sva_mx0w1, fsm_output(3));
        red_1_sva_1 <= red_1_sva_mx0w1;
        regs_regs_0_sva <= MUX_v_150_2_2(regs_regs_0_sva & regs_regs_0_lpi_2_dfm,
            fsm_output(3));
        regs_regs_2_sva <= MUX_v_150_2_2(regs_regs_2_sva & regs_regs_2_lpi_2_dfm,
            fsm_output(3));
        regs_regs_1_sva <= MUX_v_150_2_2(regs_regs_1_sva & regs_regs_1_lpi_2_dfm,
            fsm_output(3));
        regs_regs_3_sva <= MUX_v_150_2_2(regs_regs_3_sva & regs_regs_3_lpi_2_dfm,
            fsm_output(3));
        FRAME_acc_2_itm <= MUX_v_10_2_2(FRAME_acc_2_itm & STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(TO_STDLOGICVECTOR(red_1_sva_1(14))
            & TO_STDLOGICVECTOR('0') & TO_STDLOGICVECTOR(red_1_sva_1(14)) & STD_LOGIC_VECTOR'("000")
            & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(red_1_sva_1(14), 1),4))) +
            UNSIGNED(z_out), 10) + CONV_UNSIGNED(CONV_SIGNED(UNSIGNED(TO_STDLOGICVECTOR(red_1_sva_1(15))
            & STD_LOGIC_VECTOR'("000") & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(red_1_sva_1(15),
            1),5))), 10) + CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(UNSIGNED((red_1_sva_1(9
            DOWNTO 6)) & TO_STDLOGICVECTOR(red_1_sva_1(4))), 7) + CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(red_1_sva_1(6),
            1), 2) + CONV_UNSIGNED(CONV_UNSIGNED(acc_imod_sva(4), 1), 2), 3) + CONV_SIGNED(SIGNED(acc_imod_sva(6
            DOWNTO 5)), 3), 7), 7) + CONV_SIGNED(SIGNED(z_out_2), 7), 10), 10), 10)),
            fsm_output(4));
        FRAME_acc_57_psp <= MUX_v_6_2_2(FRAME_acc_57_psp & STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(CONV_SIGNED(CONV_SIGNED(green_1_sva_1(15),
            1),5)), 6) + CONV_UNSIGNED(UNSIGNED(CONV_SIGNED(CONV_SIGNED(green_1_sva_1(14),
            1),4)), 6), 6)), fsm_output(4));
        FRAME_acc_25_itm <= MUX_v_7_2_2(FRAME_acc_25_itm & STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(UNSIGNED((green_1_sva_1(9
            DOWNTO 6)) & TO_STDLOGICVECTOR(green_1_sva_1(4))), 7) + CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(green_1_sva_1(6),
            1), 2) + CONV_UNSIGNED(CONV_UNSIGNED(acc_imod_2_sva(4), 1), 2), 3) +
            CONV_SIGNED(SIGNED(acc_imod_2_sva(6 DOWNTO 5)), 3), 7), 7) + CONV_SIGNED(SIGNED(z_out_3),
            7), 7)), fsm_output(4));
        FRAME_acc_59_psp <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(CONV_SIGNED(CONV_SIGNED(blue_1_sva_1(15),
            1),5)), 6) + CONV_UNSIGNED(UNSIGNED(CONV_SIGNED(CONV_SIGNED(blue_1_sva_1(14),
            1),4)), 6), 6));
        FRAME_acc_42_itm <= STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(z_out_1) + CONV_SIGNED(CONV_SIGNED(UNSIGNED(blue_1_sva_1(9
            DOWNTO 7)), 5) + CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(SIGNED((acc_imod_4_sva(6
            DOWNTO 5)) & STD_LOGIC_VECTOR'("01")), 5) + CONV_UNSIGNED(UNSIGNED(FRAME_acc_45_sdt(3
            DOWNTO 1)), 5), 5)) & TO_STDLOGICVECTOR(FRAME_acc_45_sdt(0))) + CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
            & (acc_imod_4_sva(3 DOWNTO 0))), 6), 6)), 5), 1), 2) + CONV_SIGNED(CONV_UNSIGNED(blue_1_sva_1(5),
            1), 2), 5), 7), 7));
        FRAME_acc_4_psp_sva <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED((blue_1_sva_1(15
            DOWNTO 14)) & (blue_1_sva_1(15 DOWNTO 14)) & TO_STDLOGICVECTOR('0') &
            FRAME_acc_59_psp), 12) + CONV_UNSIGNED(SIGNED(z_out_4), 12), 12));
      END IF;
    END IF;
  END PROCESS;
  mux1h_74_nl <= MUX1HOT_v_4_3_2((red_1_sva_1(13 DOWNTO 10)) & (blue_1_sva_1(13 DOWNTO
      10)) & (green_1_sva_1(13 DOWNTO 10)), STD_LOGIC_VECTOR'((fsm_output(4)) & (fsm_output(5))
      & (fsm_output(6))));
  z_out <= STD_LOGIC_VECTOR(CONV_UNSIGNED(UNSIGNED'(UNSIGNED(mux1h_74_nl) * UNSIGNED'("101001")),
      10));
  mux_nl <= MUX_v_3_2_2(((blue_1_sva_1(7 DOWNTO 6)) & TO_STDLOGICVECTOR(blue_1_sva_1(4)))
      & (z_out_3(2 DOWNTO 0)), or_dcpl_9);
  mux_62_nl <= MUX_v_3_2_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_UNSIGNED(CONV_UNSIGNED(blue_1_sva_1(6),
      1), 2) + CONV_UNSIGNED(CONV_UNSIGNED(acc_imod_4_sva(4), 1), 2), 3) + CONV_SIGNED(SIGNED(acc_imod_4_sva(6
      DOWNTO 5)), 3), 3)) & STD_LOGIC_VECTOR'("011"), or_dcpl_9);
  z_out_1 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(((blue_1_sva_1(9
      DOWNTO 8)) AND STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(NOT((fsm_output(3))
      OR (fsm_output(2))), 1),2))) & (mux_nl)), 7) + CONV_UNSIGNED(SIGNED(mux_62_nl),
      7), 7));
  mux_58_nl <= MUX_v_3_2_2((red_1_sva_1(9 DOWNTO 7)) & STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(SHIFT_i_1_sva_3),3)),
      fsm_output(1));
  z_out_2 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(mux_58_nl), 5)
      + CONV_UNSIGNED(SIGNED(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(SIGNED((acc_imod_sva(6
      DOWNTO 5)) & STD_LOGIC_VECTOR'("01")), 5) + CONV_UNSIGNED(UNSIGNED(FRAME_acc_55_sdt(3
      DOWNTO 1)), 5), 5)) & TO_STDLOGICVECTOR(FRAME_acc_55_sdt(0))) + CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
      & (acc_imod_sva(3 DOWNTO 0))), 6), 6)), 5), 1), 2) + CONV_SIGNED(CONV_UNSIGNED(red_1_sva_1(5),
      1), 2), 2)) OR STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(fsm_output(1), 1),2))),
      5), 5));
  mux1h_73_nl <= MUX1HOT_v_3_4_2((green_1_sva_1(9 DOWNTO 7)) & i_4_sva & (TO_STDLOGICVECTOR(SHIFT_i_1_sva_2_sg1)
      & SHIFT_i_1_sva_3) & i_3_sva, STD_LOGIC_VECTOR'((fsm_output(4)) & (fsm_output(2))
      & (fsm_output(1)) & (fsm_output(3))));
  mux_59_nl <= MUX_v_2_2_2(STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(CONV_SIGNED(readindex(STD_LOGIC_VECTOR(CONV_SIGNED(SIGNED(STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(SIGNED((acc_imod_2_sva(6
      DOWNTO 5)) & STD_LOGIC_VECTOR'("01")), 5) + CONV_UNSIGNED(UNSIGNED(FRAME_acc_28_sdt(3
      DOWNTO 1)), 5), 5)) & TO_STDLOGICVECTOR(FRAME_acc_28_sdt(0))) + CONV_SIGNED(SIGNED(TO_STDLOGICVECTOR('1')
      & (acc_imod_2_sva(3 DOWNTO 0))), 6), 6)), 5), 1), 2) + CONV_SIGNED(CONV_UNSIGNED(green_1_sva_1(5),
      1), 2), 2)) & STD_LOGIC_VECTOR'("01"), (fsm_output(2)) OR (fsm_output(3)));
  z_out_3 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(mux1h_73_nl),
      5) + CONV_UNSIGNED(SIGNED((mux_59_nl) OR STD_LOGIC_VECTOR(CONV_SIGNED(CONV_SIGNED(fsm_output(1),
      1),2))), 5), 5));
  mux_61_nl <= MUX_v_7_2_2(FRAME_acc_42_itm & FRAME_acc_25_itm, fsm_output(6));
  z_out_4 <= STD_LOGIC_VECTOR(CONV_UNSIGNED(CONV_UNSIGNED(UNSIGNED(z_out), 11) +
      CONV_UNSIGNED(SIGNED(mux_61_nl), 11), 11));
END v2;

-- ------------------------------------------------------------------
--  Design Unit:    mean_vga
--  Generated from file(s):
--    7) $PROJECT_HOME/../provided_files/student_files_2015/prj2/catapult_proj/vga_blur/blur.c
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;
USE work.mean_vga_mux_pkg.ALL;


ENTITY mean_vga IS
  PORT(
    vin_rsc_z : IN STD_LOGIC_VECTOR (149 DOWNTO 0);
    vout_rsc_z : OUT STD_LOGIC_VECTOR (29 DOWNTO 0);
    clk : IN STD_LOGIC;
    en : IN STD_LOGIC;
    arst_n : IN STD_LOGIC
  );
END mean_vga;

ARCHITECTURE v2 OF mean_vga IS
  -- Default Constants

  -- Interconnect Declarations
  SIGNAL vin_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL vout_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (29 DOWNTO 0);

  SIGNAL vin_rsc_mgc_in_wire_d_1 : STD_LOGIC_VECTOR (149 DOWNTO 0);
  SIGNAL vin_rsc_mgc_in_wire_z : STD_LOGIC_VECTOR (149 DOWNTO 0);

  SIGNAL vout_rsc_mgc_out_stdreg_d_1 : STD_LOGIC_VECTOR (29 DOWNTO 0);
  SIGNAL vout_rsc_mgc_out_stdreg_z : STD_LOGIC_VECTOR (29 DOWNTO 0);

  COMPONENT mean_vga_core
    PORT(
      clk : IN STD_LOGIC;
      en : IN STD_LOGIC;
      arst_n : IN STD_LOGIC;
      vin_rsc_mgc_in_wire_d : IN STD_LOGIC_VECTOR (149 DOWNTO 0);
      vout_rsc_mgc_out_stdreg_d : OUT STD_LOGIC_VECTOR (29 DOWNTO 0)
    );
  END COMPONENT;
  SIGNAL mean_vga_core_inst_vin_rsc_mgc_in_wire_d : STD_LOGIC_VECTOR (149 DOWNTO
      0);
  SIGNAL mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d : STD_LOGIC_VECTOR (29 DOWNTO
      0);

BEGIN
  -- Default Constant Signal Assignments

  vin_rsc_mgc_in_wire : mgc_hls.mgc_ioport_comps.mgc_in_wire
    GENERIC MAP(
      rscid => 1,
      width => 150
      )
    PORT MAP(
      d => vin_rsc_mgc_in_wire_d_1,
      z => vin_rsc_mgc_in_wire_z
    );
  vin_rsc_mgc_in_wire_d <= vin_rsc_mgc_in_wire_d_1;
  vin_rsc_mgc_in_wire_z <= vin_rsc_z;

  vout_rsc_mgc_out_stdreg : mgc_hls.mgc_ioport_comps.mgc_out_stdreg
    GENERIC MAP(
      rscid => 2,
      width => 30
      )
    PORT MAP(
      d => vout_rsc_mgc_out_stdreg_d_1,
      z => vout_rsc_mgc_out_stdreg_z
    );
  vout_rsc_mgc_out_stdreg_d_1 <= vout_rsc_mgc_out_stdreg_d;
  vout_rsc_z <= vout_rsc_mgc_out_stdreg_z;

  mean_vga_core_inst : mean_vga_core
    PORT MAP(
      clk => clk,
      en => en,
      arst_n => arst_n,
      vin_rsc_mgc_in_wire_d => mean_vga_core_inst_vin_rsc_mgc_in_wire_d,
      vout_rsc_mgc_out_stdreg_d => mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d
    );
  mean_vga_core_inst_vin_rsc_mgc_in_wire_d <= vin_rsc_mgc_in_wire_d;
  vout_rsc_mgc_out_stdreg_d <= mean_vga_core_inst_vout_rsc_mgc_out_stdreg_d;

END v2;



