directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc#91 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/SHIFT:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc#115 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)#1
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/SHIFT:if:else:else:else:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)#1
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/for:acc#1 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)#2
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc#20 RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,3,1,5)#2
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul#2 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul#30 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul#32 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul#31 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:mul#33 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_mul(6,1,12,1,16)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc#105 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,10,1,12)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc#106 RESOURCE_NAME ACC1:mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(11,0,10,1,12)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/ACC1:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,2,0,3)
directive set /mean_vga/mean_vga:core/mean_vga:core:conc/for:acc RESOURCE_NAME mgc_Altera-Cyclone-III-6_beh_psr.mgc_add(3,0,2,0,3)
